"""add partial index on fire_at

Revision ID: c116b2388bed
Revises: eac0dac6f524
Create Date: 2026-08-19 15:14:00.782652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c116b2388bed"
down_revision: Union[str, Sequence[str], None] = "eac0dac6f524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_shipments_pending_fire_at",
        "shipments",
        ["fire_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_shipments_pending_fire_at",
        table_name="shipments",
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###
